### ISSUE TITLE
Failed to run it smoothly on Android

### ISSUE THREAD

**Issue by loloof64** [jusax23/flutter_stockfish_plugin#1]
Hi !

First, I would like to thank you for the Stockfish plugin. Meanwhile, when testing an hand-written example ([example repository](https://github.com/loloof64/FlutterStockfishPluginExample)) it does not runs smoothly on Android. I still don't know the issue comes from my code or your plugin.

These are the following issues I've encountered :
* when exiting the application while stockfish is still running, it seems the native threads are not closed (does it come from the fact that the 2 internal isolates could not be closed ?)
```
W/art     ( 6061): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[16,tid=6136,Native,Thread*=0xb89fee20,peer=0x12ed30a0,"1.raster"]
W/art     ( 6061): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[15,tid=6135,Native,Thread*=0xb871c120,peer=0x12ebd0a0,"1.ui"]
```
* when the application goes into background, it seems to hang, and I have to close the application manually
* if we stop Stockfish with the matching button, then trying to restart it fails.

I apologize if the issues are not descriptive enough.

**Comment by jusax23** [comment]
Hi,
I found two misstakes:
- You are using `quitok` in the `_stopStockfish` Methode to stop stockfish. The correct uci command should be `quit`. A call to _stockfish.dispose() should do the same.
- When stopping stockfish my code closes the internal connection to stockfish for good. This should be an easy fix: I will push a fix to this in a couple minutes.

At the momenent I do not get the problem, that the app starts to hang, reproduced. In my own project i use WindowListener in the code base for desktop as well as for mobile. (But this should not be necessary on android.) 
If you have more informations about that problem, i would like to hear them.

**Comment by loloof64** [comment]
Hi ! Thank you for having taken time to review my issues.

* Indeed, I've made a mistake by sending `quitok` to Stockfish' stdin
* Good news for the fix you're about to push
* As for WindowListener. It's just that, as the library has just been implemented for Windows/Linux/MacOS, I wanted to avoid relying on it for mobile targets.
* In fact, the application does not hang when it goes into background, but when I try to close it with the back button. We land on a black screen (there's just the debug banner from Flutter left)
* Also, when requesting Stockfish to stop with the 'stop stockfish' button it succeeds to do so. But then trying to restart it fails.

**Comment by jusax23** [comment]
The Problem with going to a black screen seems to come from `Navigator.pop(context);`, because this leafs nothing to show.
Replacing `SystemNavigator.pop();` does work for me, but this might not work on iOS.
Restarting stockfish should be possible with the latest version of the main branche. (I will release the fix to pub.dev in a couple days.)

**Comment by loloof64** [comment]
Thank you very much for having implemented this fix. Now the sample application does not have any issue.

Do you plan to make a release to pub.dev soon ?

**Comment by jusax23** [comment]
I released it 2h ago.

**Comment by loloof64** [comment]
Oh my bad, I just look at the releases on the Repository releases. Thank you very much 😃
