### ISSUE TITLE
stream_fix

### ISSUE THREAD

**Issue by topse** [jusax23/flutter_stockfish_plugin#4]
```
inline std::string stringify(const T& input) {
    std::ostringstream output;  // from   www  .ja va  2s  . com
    output << input;
    return output.str();
}
```

Hi,
are you sure about this? Returning a String from an object that gets destroyed after leaving the function should be a memory access error? Also look here under "notes": https://en.cppreference.com/w/cpp/io/basic_ostringstream/str

Best Regards,
Tobias

**Comment by jusax23** [comment]
Hi,
Yes I'm pretty sure about this.
This function does return a raw Datatype (no pointer or reference). So every instance of an string object should be a seperate instance in stack memory. When returning the string a copy will be created, managed by the std::string. 

Returning a c_str() pointer or a pointer from/to a local variable in stack is bad in any case. But returning the complete string should be fine.

Best Regards,
Julian
